/**
 * Type definitions for the native MPRIS bridge module
 * These will be generated by NAPI-RS after building
 */

export interface PlaybackState {
	isPlaying: boolean;
	positionMs: number;
	durationMs: number;
	volume: number;
	shuffle: boolean;
	repeat: RepeatMode;
	track: TrackInfo | null;
}

export enum RepeatMode {
	None = "None",
	Playlist = "Playlist",
	Track = "Track",
}

export interface TrackInfo {
	title: string;
	artist: string;
	album: string;
	artUrl: string | null;
	uri: string;
}

export interface SpotifydStatus {
	running: boolean;
	pid: number | null;
	authenticated: boolean;
}

export interface SpotifydConfig {
	configPath?: string;
	username?: string;
	password?: string;
	deviceName?: string;
}

/**
 * Native MPRIS Bridge Service
 * Wraps the Rust native module for MPRIS/spotifyd control
 */
export class MprisBridgeService {
	private mpris: any = null;
	private spotifyd: any = null;
	private stateCallbacks: Set<(state: PlaybackState) => void> = new Set();
	private statusCallbacks: Set<(status: SpotifydStatus) => void> = new Set();
	private isInitialized = false;

	constructor() {
		this.init().catch((error) => {
			console.error("Failed to initialize native MPRIS bridge:", error);
		});
	}

	private async init(): Promise<void> {
		try {
			// Dynamically import the native module
			// @ts-ignore - Native module will be available after build
			const native = await import("../../mpris-native/index.js");

			// Initialize spotifyd supervisor
			this.spotifyd = new native.SpotifydSupervisor();

			// Initialize MPRIS controller
			this.mpris = new native.MprisController();

			// Set up state change listener
			this.mpris.onStateChange((state: PlaybackState) => {
				for (const callback of this.stateCallbacks) {
					callback(state);
				}
			});

			// Set up status change listener
			this.spotifyd.onStatusChange((status: SpotifydStatus) => {
				for (const callback of this.statusCallbacks) {
					callback(status);
				}
			});

			this.isInitialized = true;
		} catch (error) {
			console.error("Failed to initialize native MPRIS bridge:", error);
			throw error;
		}
	}

	private async ensureInitialized(): Promise<void> {
		if (!this.isInitialized) {
			throw new Error("MPRIS bridge not yet initialized");
		}
	}

	// ─────────────────────────────────────────────────────────────
	// Connection Management
	// ─────────────────────────────────────────────────────────────

	async startSpotifyd(): Promise<void> {
		await this.ensureInitialized();
		if (!this.spotifyd) {
			throw new Error("Spotifyd supervisor not initialized");
		}
		await this.spotifyd.start();
	}

	async stopSpotifyd(): Promise<void> {
		await this.ensureInitialized();
		if (!this.spotifyd) {
			throw new Error("Spotifyd supervisor not initialized");
		}
		await this.spotifyd.stop();
	}

	async connectMpris(): Promise<void> {
		await this.ensureInitialized();
		if (!this.mpris) {
			throw new Error("MPRIS controller not initialized");
		}
		await this.mpris.connect();
	}

	getSpotifydStatus(): SpotifydStatus | null {
		if (!this.spotifyd) return null;
		return this.spotifyd.getStatus();
	}

	async checkSpotifydHealth(): Promise<boolean> {
		if (!this.spotifyd) return false;
		return await this.spotifyd.checkHealth();
	}

	// ─────────────────────────────────────────────────────────────
	// Playback Controls
	// ─────────────────────────────────────────────────────────────

	async playPause(): Promise<boolean> {
		await this.ensureInitialized();
		if (!this.mpris) {
			throw new Error("MPRIS controller not initialized");
		}
		return await this.mpris.playPause();
	}

	async next(): Promise<void> {
		await this.ensureInitialized();
		if (!this.mpris) {
			throw new Error("MPRIS controller not initialized");
		}
		await this.mpris.next();
	}

	async previous(): Promise<void> {
		await this.ensureInitialized();
		if (!this.mpris) {
			throw new Error("MPRIS controller not initialized");
		}
		await this.mpris.previous();
	}

	async seek(offsetMs: number): Promise<void> {
		await this.ensureInitialized();
		if (!this.mpris) {
			throw new Error("MPRIS controller not initialized");
		}
		await this.mpris.seek(offsetMs);
	}

	async setVolume(volume: number): Promise<void> {
		await this.ensureInitialized();
		if (!this.mpris) {
			throw new Error("MPRIS controller not initialized");
		}
		await this.mpris.setVolume(volume);
	}

	async setShuffle(shuffle: boolean): Promise<void> {
		await this.ensureInitialized();
		if (!this.mpris) {
			throw new Error("MPRIS controller not initialized");
		}
		await this.mpris.setShuffle(shuffle);
	}

	async setRepeat(repeat: RepeatMode): Promise<void> {
		await this.ensureInitialized();
		if (!this.mpris) {
			throw new Error("MPRIS controller not initialized");
		}
		await this.mpris.setRepeat(repeat);
	}

	// ─────────────────────────────────────────────────────────────
	// State Management
	// ─────────────────────────────────────────────────────────────

	getState(): PlaybackState | null {
		if (!this.mpris) return null;
		return this.mpris.getState();
	}

	onStateChange(callback: (state: PlaybackState) => void): () => void {
		this.stateCallbacks.add(callback);
		// Return unsubscribe function
		return () => {
			this.stateCallbacks.delete(callback);
		};
	}

	onStatusChange(callback: (status: SpotifydStatus) => void): () => void {
		this.statusCallbacks.add(callback);
		// Return unsubscribe function
		return () => {
			this.statusCallbacks.delete(callback);
		};
	}

	// ─────────────────────────────────────────────────────────────
	// Cleanup
	// ─────────────────────────────────────────────────────────────

	async cleanup(): Promise<void> {
		this.stateCallbacks.clear();
		this.statusCallbacks.clear();

		if (this.spotifyd) {
			try {
				await this.spotifyd.stop();
			} catch (error) {
				console.error("Error stopping spotifyd:", error);
			}
		}
	}
}

// Singleton instance
let instance: MprisBridgeService | null = null;

export function getMprisBridgeService(): MprisBridgeService {
	if (!instance) {
		instance = new MprisBridgeService();
	}
	return instance;
}
